#ifndef NOTSUITABLEWIFIADAPTERFOUNDVENICEEXCEPTION_H
#define NOTSUITABLEWIFIADAPTERFOUNDVENICEEXCEPTION_H


class NotSuitableWifiAdapterFoundVeniceException
{
public:
    NotSuitableWifiAdapterFoundVeniceException();
};

#endif // NOTSUITABLEWIFIADAPTERFOUNDVENICEEXCEPTION_H
